Update monasca-agent init scripts
Brings init.d and supervisor.conf up to date

Change-Id: I5bf8c03d2c0c6ff0962a88747b9def82c57e65d1

diff --git a/templates/monasca-agent.init.erb b/templates/monasca-agent.init.erb
--- a/templates/monasca-agent.init.erb
+++ b/templates/monasca-agent.init.erb
@@ -11,22 +11,23 @@
 ### END INIT INFO
 
 . <%= @virtual_env %>/bin/activate
-. /lib/lsb/init-functions
-PATH=$PATH:/sbin # add the location of start-stop-daemon on Debian
-export PYTHONPATH=$PYTHONPATH:/usr/monasca/agent/
 
-AGENTPATH="<%= @virtual_env %>/bin/monasca-collector"
-AGENTCONF="/etc/monasca/agent/agent.yaml"
-MONASCASTATSDPATH="<%= @virtual_env %>/bin/monasca-statsd"
-AGENTUSER="monasca-agent"
-FORWARDERPATH="<%= @virtual_env %>/bin/monasca-forwarder"
+PATH=$PATH:/usr/local/bin # supervisord might live here
+PATH=$PATH:/sbin
+
+AGENTPATH="<%= virtual_env %>/bin/monasca-collector"
+AGENTCONF="<%= agent_dir %>/agent.yaml"
+MONASCASTATSDPATH="<%= virtual_env %>/bin/monasca-statsd"
+AGENTUSER="<%= agent_user %>"
+FORWARDERPATH="<%= virtual_env %>/bin/monasca-forwarder"
 NAME="monasca-agent"
 DESC="Monasca Monitoring Agent"
-AGENT_PID_PATH="/var/run/monasca-agent.pid"
-SUPERVISOR_PIDFILE="/var/run/monasca-agent-supervisord.pid"
-SUPERVISOR_FILE="<%= @virtual_env %>/share/monasca/agent/supervisor.conf"
+AGENT_PID_PATH="/var/tmp/monasca-agent.pid"
+SUPERVISOR_PIDFILE="/var/tmp/monasca-agent-supervisord.pid"
+SUPERVISOR_FILE="<%= agent_dir %>/supervisor.conf"
 SUPERVISOR_SOCK="/var/tmp/monasca-agent-supervisor.sock"
-SUPERVISORD=$(which supervisord)
+SUPERVISORD="<%= virtual_env %>/bin/supervisord"
+SUPERVISORCTL="<%= virtual_env %>/bin/supervisorctl"
 
 # This script is considered a configuration file and will not be
 # removed by dpkg unless the --purge option it set. Therefore we
@@ -44,7 +45,7 @@ check_status() {
         # same as the number of programs specified in the supervisor config
         # file:
 
-        supervisor_processes=$(supervisorctl -c $SUPERVISOR_FILE status)
+        supervisor_processes=$($SUPERVISORCTL -c $SUPERVISOR_FILE status)
         supervisor_processes=$(echo "$supervisor_processes" |
                                        grep -v pup |
                                        grep $NAME |
@@ -82,15 +83,15 @@ case "$1" in
 
         su $AGENTUSER -c "$AGENTPATH configcheck" > /dev/null
         if [ $? -ne 0 ]; then
-            log_daemon_msg "Invalid check configuration. Please run sudo /etc/init.d/monasca-agent configtest for more details."
-            log_daemon_msg "Resuming starting process."
+            echo "Invalid check configuration. Please run sudo /etc/init.d/monasca-agent configtest for more details."
+            echo "Resuming starting process."
         fi
 
 
-        log_daemon_msg "Starting $DESC (using supervisord)" "$NAME"
-        start-stop-daemon --start --quiet --oknodo --exec $SUPERVISORD -- -c $SUPERVISOR_FILE --pidfile $SUPERVISOR_PIDFILE
+        echo "Starting $DESC (using supervisord)" "$NAME"
+        $SUPERVISORD -c $SUPERVISOR_FILE -u $AGENTUSER --pidfile $SUPERVISOR_PIDFILE
         if [ $? -ne 0 ]; then
-            log_end_msg 1
+            exit $?
         fi
 
         # check if the agent is running once per second for 10 seconds
@@ -98,7 +99,6 @@ case "$1" in
         while [ $retries -gt 1 ]; do
           if check_status > /dev/null; then
               # We've started up successfully. Exit cleanly
-              log_end_msg 0
               exit 0
           else
               retries=$(($retries - 1))
@@ -106,23 +106,27 @@ case "$1" in
           fi
         done
         # After 10 tries the agent didn't start. Report an error
-        log_end_msg 1
+        exit 1
         check_status # report what went wrong
         $0 stop
         exit 1
         ;;
     stop)
 
-        log_daemon_msg "Stopping $DESC (stopping supervisord)" "$NAME"
-        start-stop-daemon --stop --retry 30 --quiet --oknodo --pidfile $SUPERVISOR_PIDFILE
-   
-        log_end_msg $?
+        echo "Stopping $DESC (stopping supervisord)" "$NAME"
+        if [ -e $SUPERVISOR_PIDFILE ]; then
+          kill `cat $SUPERVISOR_PIDFILE`
+        else
+          echo "Pid file $SUPERVISOR_PIDFILE not found, nothing to stop"
+        fi
+
+        exit $?
 
         ;;
 
     info)
         shift # Shift 'info' out of args so we can pass any
-              # addtional options to the real command
+              # additional options to the real command
               # (right now only monasca-agent supports additional flags)
         su $AGENTUSER -c "$AGENTPATH info $@"
         COLLECTOR_RETURN=$?
@@ -139,6 +143,7 @@ case "$1" in
 
     restart|force-reload)
         $0 stop
+        sleep 1
         $0 start
         ;;
 
@@ -159,8 +164,7 @@ case "$1" in
         ;;
 
     *)
-        N=/etc/init.d/$NAME
-        echo "Usage: $N {start|stop|restart|info|status|configcheck|configtest|jmx}"
+        echo "Usage: /etc/init.d/$NAME {{start|stop|restart|info|status|configcheck|configtest|jmx}}"
         exit 1
         ;;
 esac
